import 'dart:convert';
import '../services/api_service.dart';

class StorageService {
  static final ApiService _apiService = ApiService();

  // User data methods
  static Future<Map<String, String>?> getUserData() async {
    try {
      final userData = await _apiService.getUserProfile();
      return {
        'name': userData['name']?.toString() ?? '',
        'email': userData['email']?.toString() ?? '',
        'phone': userData['phone']?.toString() ?? '',
        'avatar': userData['avatar']?.toString() ?? '',
      };
    } catch (e) {
      // Return null if not logged in or error occurs
      return null;
    }
  }

  static Future<void> saveUserData(Map<String, String> userData) async {
    await _apiService.updateUserProfile(userData);
  }

  // Booking methods
  static Future<void> saveBooking(Map<String, dynamic> booking) async {
    await _apiService.createBooking(booking);
  }

  static Future<List<Map<String, dynamic>>> getBookings() async {
    try {
      return await _apiService.getUserBookings();
    } catch (e) {
      return [];
    }
  }

  static Future<bool> isTimeSlotBooked(String salonId, DateTime date, String time) async {
    try {
      final availability = await _apiService.getSalonAvailability(
        salonId,
        '${date.year}-${date.month.toString().padLeft(2, '0')}-${date.day.toString().padLeft(2, '0')}',
      );
      
      return availability.any((slot) => 
        slot['time'] == time && slot['booked'] == true
      );
    } catch (e) {
      return false;
    }
  }

  static Future<void> updateBookingStatus(String bookingId, String status) async {
    await _apiService.updateBookingStatus(bookingId, status);
  }

  static Future<String> getNextBookingId() async {
    // This will be generated by the backend
    try {
      final bookings = await getBookings();
      return (bookings.length + 1).toString();
    } catch (e) {
      return '1';
    }
  }

  // Salon methods
  static Future<List<Map<String, String>>> getSalons({Map<String, String>? filters}) async {
    try {
      final salons = await _apiService.getSalons(filters: filters);
      return salons.map((salon) => {
        'id': salon['id']?.toString() ?? '',
        'name': salon['name']?.toString() ?? '',
        'rating': salon['rating']?.toString() ?? '',
        'distance': salon['distance']?.toString() ?? '',
        'status': salon['status']?.toString() ?? '',
        'icon': salon['icon']?.toString() ?? 'content_cut',
        'address': salon['address']?.toString() ?? '',
        'phone': salon['phone']?.toString() ?? '',
        'hours': salon['hours']?.toString() ?? '',
        'waitingTime': salon['waitingTime']?.toString() ?? '',
        'homeServiceAvailable': salon['homeServiceAvailable']?.toString() ?? 'false',
      }).toList();
    } catch (e) {
      return [];
    }
  }

  static Future<void> saveSalons(List<Map<String, String>> salons) async {
    // Salons are managed by the backend, no local saving needed
  }

  // Favorites methods
  static Future<void> addToFavorites(Map<String, String> salon) async {
    await _apiService.addToFavorites(salon['id']!);
  }

  static Future<void> removeFromFavorites(String salonName) async {
    // First get the salon ID by name, then remove
    try {
      final salons = await getSalons();
      final salon = salons.firstWhere((s) => s['name'] == salonName);
      await _apiService.removeFromFavorites(salon['id']!);
    } catch (e) {
      // Handle error
    }
  }

  static Future<List<Map<String, String>>> getFavorites() async {
    try {
      final favorites = await _apiService.getFavorites();
      return favorites.map((fav) => {
        'id': fav['id']?.toString() ?? '',
        'name': fav['name']?.toString() ?? '',
        'rating': fav['rating']?.toString() ?? '',
        'distance': fav['distance']?.toString() ?? '',
        'status': fav['status']?.toString() ?? '',
        'icon': fav['icon']?.toString() ?? 'content_cut',
        'address': fav['address']?.toString() ?? '',
        'phone': fav['phone']?.toString() ?? '',
        'hours': fav['hours']?.toString() ?? '',
      }).toList();
    } catch (e) {
      return [];
    }
  }

  static Future<bool> isFavorite(String salonName) async {
    try {
      final favorites = await getFavorites();
      return favorites.any((fav) => fav['name'] == salonName);
    } catch (e) {
      return false;
    }
  }

  // Notifications methods
  static Future<void> addNotification(Map<String, dynamic> notification) async {
    // Notifications are managed by the backend
  }

  static Future<List<Map<String, dynamic>>> getNotifications() async {
    try {
      return await _apiService.getNotifications();
    } catch (e) {
      return [];
    }
  }

  static Future<void> markNotificationAsRead(int index) async {
    try {
      final notifications = await getNotifications();
      if (index < notifications.length) {
        await _apiService.markNotificationAsRead(notifications[index]['id'].toString());
      }
    } catch (e) {
      // Handle error
    }
  }

  static Future<void> markAllNotificationsAsRead() async {
    try {
      await _apiService.markAllNotificationsAsRead();
    } catch (e) {
      // Handle error
    }
  }

  // Authentication methods
  static Future<Map<String, dynamic>> login(String email, String password) async {
    return await _apiService.login(email, password);
  }

  static Future<Map<String, dynamic>> register(Map<String, dynamic> userData) async {
    return await _apiService.register(userData);
  }

  static Future<void> logout() async {
    await _apiService.logout();
  }

  static Future<bool> isLoggedIn() async {
    return await _apiService.isLoggedIn();
  }

  // Clear all data (logout)
  static Future<void> clearAllData() async {
    await logout();
  }

  // Payment methods
  static Future<Map<String, dynamic>> createPaymentIntent(Map<String, dynamic> paymentData) async {
    return await _apiService.createPaymentIntent(paymentData);
  }

  static Future<Map<String, dynamic>> confirmPayment(String paymentIntentId) async {
    return await _apiService.confirmPayment(paymentIntentId);
  }

  // Salon services
  static Future<List<Map<String, dynamic>>> getSalonServices(String salonId) async {
    try {
      return await _apiService.getSalonServices(salonId);
    } catch (e) {
      return [];
    }
  }

  // Salon availability
  static Future<List<Map<String, dynamic>>> getSalonAvailability(String salonId, String date) async {
    try {
      return await _apiService.getSalonAvailability(salonId, date);
    } catch (e) {
      return [];
    }
  }
}
